server:
  port: 9055
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
  
  
spring:
  application:
    name: Api-gateway-service
    
  cloud:
    gateway:
      routes:
      - id: admin-contact-service
        uri: lb://admin-contact-service
        predicates:
        - Path=/admin/**  
      - id: booking-order-service
        uri: lb://booking-order-service
        predicates:
        - Path=/orders/**
      - id: train-service
        uri: lb://train-service
        predicates:
        - Path=/trains/**
      - id: payment-service
        uri: lb://payment-service
        predicates:
        - Path=/Payment/**
      - id: user-service
        uri: lb://user-service
        predicates:
        - Path=/user/**